#!/bin/bash

# ALL-RECON - SUBDOMAIN CLEANER QUICK GUIDE

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  [CLEAN] SUBDOMAIN CLEANER - QUICK REFERENCE                       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "WHAT IT DOES:"
echo "─────────────────────────────────────────────────────────────────"
echo "[OK] Removes duplicate subdomains"
echo "[OK] Resolves IP addresses"
echo "[OK] Filters invalid/unresolved entries"
echo "[OK] Groups results by IP"
echo "[OK] Exports to CSV/JSON"
echo "[OK] Generates clean, organized output"
echo ""

echo "VIA MAIN TOOL (Interactive):"
echo "─────────────────────────────────────────────────────────────────"
echo "$ ./all_recon.sh"
echo "Select: 3 (Subdomain Discovery Workflow)"
echo "Option: 1 (Run Discovery) or 2 (Clean Results) or 3 (View Clean)"
echo ""
echo "After discovery:"
echo "  -> Select 'Y' to clean results automatically"
echo "  -> Or manually clean: Option 2"
echo ""

echo "DIRECT MODULE USAGE:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Comprehensive cleaning (all steps):"
echo "  ./modules/subdomain_cleaner.sh output/subdomains_*/ all"
echo ""
echo "Extract unique subdomains only:"
echo "  ./modules/subdomain_cleaner.sh output/subdomains_*/ extract"
echo ""
echo "Deduplicate and resolve IPs:"
echo "  ./modules/subdomain_cleaner.sh output/subdomains_*/ deduplicate"
echo ""
echo "Active hosts only:"
echo "  ./modules/subdomain_cleaner.sh output/subdomains_*/ active"
echo ""
echo "Group by IP address:"
echo "  ./modules/subdomain_cleaner.sh output/subdomains_*/ group"
echo ""
echo "Export to CSV:"
echo "  ./modules/subdomain_cleaner.sh output/subdomains_*/ csv"
echo ""
echo "Export to JSON:"
echo "  ./modules/subdomain_cleaner.sh output/subdomains_*/ json"
echo ""

echo "OUTPUT:"
echo "─────────────────────────────────────────────────────────────────"
echo "Results saved to: output/clean_subdomains_YYYYMMDD_HHMMSS/"
echo ""
echo "Generated files:"
echo "  - extracted_subdomains_*.txt      - Unique subdomains"
echo "  - deduplicated_*.txt              - With IP addresses"
echo "  - active_subdomains_*.txt         - Resolved hosts only"
echo "  - grouped_by_ip_*.txt             - Organized by IP"
echo "  - subdomains_*.csv                - Spreadsheet format"
echo "  - subdomains_*.json               - JSON format"
echo "  - CLEANING_SUMMARY_*.txt          - Summary report"
echo ""

echo "TYPICAL WORKFLOW:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Step 1: Discover subdomains"
echo "  $ ./all_recon.sh -> Option 3 -> Discover"
echo ""
echo "Step 2: Clean results (automatic or manual)"
echo "  $ [Answer Y] or manually run cleaner"
echo ""
echo "Step 3: Review cleaned data"
echo "  $ cat output/clean_subdomains_*/active_subdomains_*.txt"
echo ""
echo "Step 4: Use for next phase"
echo "  $ cat output/clean_subdomains_*/subdomains_*.csv"
echo ""

echo "EXAMPLE OUTPUT:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "SUBDOMAIN                          | IP ADDRESS         | STATUS"
echo "───────────────────────────────────┼────────────────────┼──────────"
echo "www.example.com                   | 93.184.216.34      | [OK] ACTIVE"
echo "mail.example.com                  | 93.184.216.35      | [OK] ACTIVE"
echo "ftp.example.com                   | N/A                | [WARN] UNRESOLVED"
echo "admin.example.com                 | 93.184.216.36      | [OK] ACTIVE"
echo ""

echo "CUSTOMIZATION:"
echo "─────────────────────────────────────────────────────────────────"
echo "Edit: config/subdomain_cleaner.conf"
echo ""
echo "Key options:"
echo "  - REMOVE_UNRESOLVED=\"true\"     - Skip unresolved hosts"
echo "  - EXCLUDE_PRIVATE_IPS=\"true\"   - Filter private ranges"
echo "  - GROUP_BY_IP=\"true\"           - Organize output by IP"
echo "  - PARALLEL_THREADS=10            - Increase speed"
echo ""

echo "═════════════════════════════════════════════════════════════════"
