#!/bin/bash

# ALL-RECON SUBDOMAIN DISCOVERY QUICK REFERENCE

echo "🔍 ALL-RECON - SUBDOMAIN DISCOVERY MODULE"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "QUICK USAGE:"
echo ""
echo "Via Main Tool:"
echo "  ./all_recon.sh"
echo "  Select option 3: Subdomain Discovery"
echo ""
echo "Direct Module:"
echo "  ./modules/subdomain_finder.sh <domain> <scan_type>"
echo ""

echo "SCAN TYPES:"
echo "  dns       - DNS zone transfer & enumeration"
echo "  common    - Common subdomain brute force"
echo "  reverse   - Reverse IP lookup"
echo "  records   - Public DNS records scan"
echo "  cert      - Certificate transparency logs"
echo "  all       - Comprehensive scan (all methods)"
echo ""

echo "EXAMPLES:"
echo ""
echo "  # Comprehensive scan of example.com"
echo "  ./modules/subdomain_finder.sh example.com all"
echo ""
echo "  # Only common subdomains"
echo "  ./modules/subdomain_finder.sh example.com common"
echo ""
echo "  # Certificate transparency only"
echo "  ./modules/subdomain_finder.sh example.com cert"
echo ""
echo "  # Via main tool (interactive)"
echo "  ./all_recon.sh"
echo ""

echo "OUTPUT LOCATIONS:"
echo "  Results:  output/subdomains_YYYYMMDD_HHMMSS/"
echo "  Logs:     logs/subdomain_YYYYMMDD_HHMMSS.log"
echo ""

echo "WHAT IT DISCOVERS:"
echo "  ✅ DNS zone transfers"
echo "  ✅ Reverse DNS records"
echo "  ✅ Common subdomain variations"
echo "  ✅ Mail servers (MX records)"
echo "  ✅ Name servers (NS records)"
echo "  ✅ Text records (TXT, SPF, DMARC)"
echo "  ✅ CNAME records"
echo "  ✅ SSL/TLS certificates"
echo ""

echo "CONFIGURATION:"
echo "  Edit: config/subdomain_discovery.conf"
echo "  • Enable/disable methods"
echo "  • Adjust timeout values"
echo "  • Customize alert thresholds"
echo ""

echo "═══════════════════════════════════════════════════════════"
